# -*- coding: utf-8 -*-
"""Aplicação - Desenhos - Parte 1 / Application - Drawings - Part 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kZqKmSeQVuSJ-FeizT4vNN1FIMcjlUUn
"""

# Para ver os comentários e entender o código, veja o vídeo associado a ele.
# To see the comments and understand the code, watch the associated video.

# Link para o vídeo / Link to the video: https://youtu.be/E-1LHrxElBw

# License: Creative Commons (CC BY 4.0)

# Autor / Author: Nicolas Henrique (nh947760@gmail.com)

"""Fonte das imagem / Source of the image: Imagem (https://tinyurl.com/fimed-fi-fp) de ddraw no Freepik (www.freepik.com)"""

import cv2
import matplotlib.pyplot as plt

figure = cv2.imread("hands_statues.jpg")

figure = cv2.cvtColor(figure, cv2.COLOR_BGR2RGB)

plt.imshow(figure)
plt.show()

# Primeira modificação da imagem
# First modification of the image

# Fazendo alterações nas camadas de cores da imagem. Na variável figure foi armazenada a imagem original.
# Making changes to the color layers of the image. The original image was stored in the figure variable.

figure_cp = figure.copy()
figure_cp[:,:,0] = figure[:,:,1]
figure_cp[:,:,1] = figure[:,:,2]
figure_cp[:,:,2] = figure[:,:,2]

fig,axs = plt.subplots(1, 2, layout='constrained', figsize = [13,13])

axs[0].imshow(figure)

axs[0].set_title('Imagem original / Original Image')

axs[0].set_axis_off()

axs[1].imshow(figure_cp)

axs[1].set_title('Imagem modificada / Modified Image')

axs[1].set_axis_off()

plt.show()

# Segunda modificação da imagem
# Second modification of the image

# Alterando as camadas de cores mais uma vez, de maneira análoga a que foi feita anteriormente. E o processo de exibição dos resultados
# é idêntico ao anterior.

# Changing the color layers once again, in a manner similar to what was done previously. And the process of displaying the results is
# identical to the previous one.

figure_cp = figure.copy()
figure_cp[:,:,0] = figure[:,:,0]
figure_cp[:,:,1] = figure[:,:,2]
figure_cp[:,:,2] = figure[:,:,1]

fig,axs = plt.subplots(1, 2, layout='constrained', figsize = [13,13])

axs[0].imshow(figure)

axs[0].set_title('Imagem original / Original Image')

axs[0].set_axis_off()

axs[1].imshow(figure_cp)

axs[1].set_title('Imagem modificada / Modified Image')

axs[1].set_axis_off()

plt.show()

# Terceira modificação da imagem
# Third modification of the image

figure_cp = figure.copy()

figure_cp[:,:,0] = figure[:,:,1]
figure_cp[:,:,1] = figure[:,:,1]
figure_cp[:,:,2] = figure[:,:,2]

fig,axs = plt.subplots(1, 2, layout='constrained', figsize = [13,13])

axs[0].imshow(figure)

axs[0].set_title('Imagem original / Original Image')

axs[0].set_axis_off()

axs[1].imshow(figure_cp)

axs[1].set_title('Imagem modificada / Modified Image')

axs[1].set_axis_off()

plt.show()

# Quarta modificação da imagem
# Fourth modification of the image

figure_cp = figure.copy()

figure_cp[:,:,0] = figure[:,:,0]
figure_cp[:,:,1] = figure[:,:,2]
figure_cp[:,:,2] = figure[:,:,0]

fig,axs = plt.subplots(1, 2, layout='constrained', figsize = [13,13])

axs[0].imshow(figure)

axs[0].set_title('Imagem original / Original Image')

axs[0].set_axis_off()

axs[1].imshow(figure_cp)

axs[1].set_title('Imagem modificada / Modified Image')

axs[1].set_axis_off()

plt.show()

# Quinta modificação da imagem
# Fifth modification of the image

figure_cp = figure.copy()

figure_cp[:,:,0] = figure[:,:,2]
figure_cp[:,:,1] = figure[:,:,1]
figure_cp[:,:,2] = figure[:,:,2]

fig,axs = plt.subplots(1, 2, layout='constrained', figsize = [13,13])

axs[0].imshow(figure)

axs[0].set_title('Imagem original / Original Image')

axs[0].set_axis_off()

axs[1].imshow(figure_cp)

axs[1].set_title('Imagem modificada / Modified Image')

axs[1].set_axis_off()

plt.show()

# Sexta modificação da imagem
# Sixth modification of the image

figure_cp = figure.copy()

figure_cp[:,:,0] = figure[:,:,0]
figure_cp[:,:,1] = figure[:,:,1]
figure_cp[:,:,2] = figure[:,:,1]

fig,axs = plt.subplots(1, 2, layout='constrained', figsize = [13,13])

axs[0].imshow(figure)

axs[0].set_title('Imagem original / Original Image')

axs[0].set_axis_off()

axs[1].imshow(figure_cp)

axs[1].set_title('Imagem modificada / Modified Image')

axs[1].set_axis_off()

plt.show()

import numpy as np
from google.colab.patches import cv2_imshow

# Sétima modificação efetuada na imagem
# Seventh modification made to the image

# Obtendo os contornos da imagem
# Obtaining the image contours

figure = cv2.cvtColor(figure, cv2.COLOR_RGB2BGR)

high_booster = np.array([
    [-1,-1,-1],
    [-1,8,-1],
    [-1,-1,-1]
])

figure_filtered = cv2.filter2D(figure, -1, high_booster)

cv2_imshow(figure_filtered)

# Oitava modificação efetuada na imagem
# Eighth modification made to the image

# Mesma modificação feita no passo anterior, mas agora efetuada na imagem convertinda para cinza
# The same modification made in the previous step, but now applied to the image converted to grayscale

figure_gray = cv2.cvtColor(figure, cv2.COLOR_BGR2GRAY)

high_booster = np.array([
    [-1,-1,-1],
    [-1,8,-1],
    [-1,-1,-1]
])

figure_filtered = cv2.filter2D(figure_gray, -1, high_booster)

cv2_imshow(figure_filtered)

# Nona modificação efetuada na imagem
# Ninth modification made to the image

# Aumentando para 255 a intensidade dos pixels com intensidade superior a 100
# Increasing the intensity of pixels with an intensity greater than 100 to 255

height = figure_filtered.shape[0]

width = figure_filtered.shape[1]

figure_filtered_cp = figure_filtered.copy()

for i in range(height):
  for j in range(width):
    if figure_filtered[i,j]>100:
      figure_filtered_cp[i,j]=255


cv2_imshow(figure_filtered_cp)

# Décima modificação efetuada na imagem
# Tenth modification made to the image

# Esta modificação segue os mesmos passos da anterior, a diferença é que o aumento da intensidade para 255 ocorrerá nos pixels com
# intensidade superior a 50

# This modification follows the same steps as the previous one; the difference is that the increase in intensity to 255 will occur in
# pixels with an intensity greater than 50.

height = figure_filtered.shape[0]
width = figure_filtered.shape[1]

figure_filtered_cp = figure_filtered.copy()

for i in range(height):
  for j in range(width):
    if figure_filtered[i,j]>50:
      figure_filtered_cp[i,j]=255


cv2_imshow(figure_filtered_cp)

# Décima primeira modificação efetuada na imagem
# Eleventh modification made to the image

# Aumentando o volume dos contornos quando o limiar de intensidade para realizar a modificação da intensidade dos pixels é 100
# Increasing the volume of the outlines when the intensity threshold for modifying pixel intensity is 100

height = figure_filtered.shape[0]

width = figure_filtered.shape[1]

figure_filtered_cp = figure_filtered.copy()

for i in range(height):
  for j in range(width):
    if figure_filtered[i,j]>100:
      figure_filtered_cp[i,j]=255

dim = 5

c=1/9

mask = np.ones((dim,dim))*c

figure_filtered_cp = cv2.filter2D(figure_filtered_cp, -1, mask)

cv2_imshow(figure_filtered_cp)

# Décima segunda modificação efetuada na imagem
# Twelfth modification made to the image

# Repetindo os mesmos passos da modificação passada, mas agora com o limiar de intensidade igual a 50
# Repeating the same steps as the previous modification, but now with the intensity threshold equal to 50

height = figure_filtered.shape[0]
width = figure_filtered.shape[1]

figure_filtered_cp = figure_filtered.copy()

for i in range(height):
  for j in range(width):
    if figure_filtered[i,j]>50:
      figure_filtered_cp[i,j]=255

dim = 5

c=1/9

mask = np.ones((dim,dim))*c

figure_filtered_cp = cv2.filter2D(figure_filtered_cp, -1, mask)

cv2_imshow(figure_filtered_cp)
