# -*- coding: utf-8 -*-
"""Aplicação 1 - Desenhos - Parte 3 / Application 1 - Drawings - Part 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DTQuT93fg40HtHhK2xLeoeXBtwqHGGI-
"""

# Para ver os comentários e entender o código, veja o vídeo associado a ele.
# To see the comments and understand the code, watch the associated video.

# Link para o vídeo / Link to the video: https://youtu.be/E-1LHrxElBw

# License: Creative Commons (CC BY 4.0)

# Autor / Author: Nicolas Henrique (nh947760@gmail.com)

"""Fonte das imagem / Source of the image: [Imagem](https://tinyurl.com/fimed-th-fp) de macrovector no [Freepik](www.freepik.com)"""

import cv2
import matplotlib.pyplot as plt

figure = cv2.imread("knight.jpg")

figure = cv2.cvtColor(figure, cv2.COLOR_BGR2RGB)

plt.imshow(figure)
plt.show()

# Primeira modificação efetuada na terceira imagem
# First modification made to the third image

# Mesmos passos da primeiras modificações realizadas nas imagens anteriores
# Same steps as the initial modifications made to the previous images

figure_cp = figure.copy()
figure_cp[:,:,0] = figure[:,:,1]
figure_cp[:,:,1] = figure[:,:,2]
figure_cp[:,:,2] = figure[:,:,2]

fig,axs = plt.subplots(1, 2, layout='constrained', figsize = [13,13])

axs[0].imshow(figure)

axs[0].set_title('Imagem original / Original Image')

axs[0].set_axis_off()

axs[1].imshow(figure_cp)

axs[1].set_title('Imagem modificada / Modified Image')

axs[1].set_axis_off()

plt.show()

# Segunda modificação efetuada na terceira imagem
# Second modification made to the third image

# Mesmos passos das segundas modificações realizadas nas imagens anteriores
# Same steps as the second modifications performed on the previous images

figure_cp = figure.copy()
figure_cp[:,:,0] = figure[:,:,0]
figure_cp[:,:,1] = figure[:,:,2]
figure_cp[:,:,2] = figure[:,:,1]

fig,axs = plt.subplots(1, 2, layout='constrained', figsize = [13,13])

axs[0].imshow(figure)

axs[0].set_title('Imagem original / Original Image')

axs[0].set_axis_off()

axs[1].imshow(figure_cp)

axs[1].set_title('Imagem modificada / Modified Image')

axs[1].set_axis_off()

plt.show()

# Terceira modificação efetuada na terceira imagem
# Third modification made to the third image

# Mesmos passos das terceiras modificações realizadas nas imagens anteriores
# Same steps as the third modifications performed on the previous images

figure_cp = figure.copy()
figure_cp[:,:,0] = figure[:,:,1]
figure_cp[:,:,1] = figure[:,:,1]
figure_cp[:,:,2] = figure[:,:,2]

fig,axs = plt.subplots(1, 2, layout='constrained', figsize = [13,13])

axs[0].imshow(figure)

axs[0].set_title('Imagem original / Original Image')

axs[0].set_axis_off()

axs[1].imshow(figure_cp)

axs[1].set_title('Imagem modificada / Modified Image')

axs[1].set_axis_off()

plt.show()

# Quarta modificação efetuada na terceira imagem
# Fourth modification made to the third image

# Mesmos passos das quartas modificações realizadas nas imagens anteriores
# Same steps as the fourth modifications performed on the previous images

figure_cp = figure.copy()
figure_cp[:,:,0] = figure[:,:,0]
figure_cp[:,:,1] = figure[:,:,2]
figure_cp[:,:,2] = figure[:,:,0]

fig,axs = plt.subplots(1, 2, layout='constrained', figsize = [13,13])

axs[0].imshow(figure)

axs[0].set_title('Imagem original / Original Image')

axs[0].set_axis_off()

axs[1].imshow(figure_cp)

axs[1].set_title('Imagem modificada / Modified Image')

axs[1].set_axis_off()

plt.show()

# Quinta modificação efetuada na terceira imagem
# Fifth modification made to the third image

# Mesmos passos das quintas modificações realizadas nas imagens anteriores
# Same steps as the fifth modifications performed on the previous images

figure_cp = figure.copy()
figure_cp[:,:,0] = figure[:,:,2]
figure_cp[:,:,1] = figure[:,:,1]
figure_cp[:,:,2] = figure[:,:,2]

fig,axs = plt.subplots(1, 2, layout='constrained', figsize = [13,13])

axs[0].imshow(figure)

axs[0].set_title('Imagem original / Original Image')

axs[0].set_axis_off()

axs[1].imshow(figure_cp)

axs[1].set_title('Imagem modificada / Modified Image')

axs[1].set_axis_off()

plt.show()

# Sexta modificação efetuada na terceira imagem
# Sixth modification made to the third image

# Mesmos passos das sextas modificações realizadas nas imagens anteriores
# Same steps as the sixth modifications performed on the previous images

figure_cp = figure.copy()
figure_cp[:,:,0] = figure[:,:,0]
figure_cp[:,:,1] = figure[:,:,1]
figure_cp[:,:,2] = figure[:,:,1]

fig,axs = plt.subplots(1, 2, layout='constrained', figsize = [13,13])

axs[0].imshow(figure)

axs[0].set_title('Imagem original / Original Image')

axs[0].set_axis_off()

axs[1].imshow(figure_cp)

axs[1].set_title('Imagem modificada / Modified Image')

axs[1].set_axis_off()

plt.show()

import numpy as np
from google.colab.patches import cv2_imshow

# Sétima modificação efetuada na terceira imagem
# Seventh modification made to the third image

# Mesmos passos das sétimas modificações realizadas nas imagens anteriores
# Same steps as the seventh modifications performed on the previous images

figure = cv2.cvtColor(figure, cv2.COLOR_RGB2BGR)

high_booster = np.array([
    [-1,-1,-1],
    [-1,8,-1],
    [-1,-1,-1]
])

figure_filtered = cv2.filter2D(figure, -1, high_booster)

cv2_imshow(figure_filtered)

# Oitava modificação efetuada na terceira imagem
# Eighth modification made to the third image

# Mesmos passos das oitavas modificações realizadas nas imagens anteriores
# Same steps as the eighth modifications performed on the previous images

figure_gray = cv2.cvtColor(figure, cv2.COLOR_BGR2GRAY)

high_booster = np.array([
    [-1,-1,-1],
    [-1,8,-1],
    [-1,-1,-1]
])

figure_filtered = cv2.filter2D(figure_gray, -1, high_booster)
cv2_imshow(figure_filtered)

# Nona modificação efetuada na imagem
# Ninth modification made to the image

# Mesmos passos das nonas modificações realizada nas imagens anteriores
# Same steps as the ninth modifications performed on the previous images.

height = figure_filtered.shape[0]

width = figure_filtered.shape[1]

figure_filtered_cp = figure_filtered.copy()

for i in range(height):
  for j in range(width):
    if figure_filtered[i,j]>100:
      figure_filtered_cp[i,j]=255


cv2_imshow(figure_filtered_cp)

# Décima modificação efetuada na terceira imagem
# Tenth modification made to the third image

# Mesmos passos das décimas modificações realizada nas imagens anteriores, com a diferença do limiar de intensidade ser 20 dessa vez
# Same steps as the tenth modifications performed on the previous images.

height = figure_filtered.shape[0]

width = figure_filtered.shape[1]

figure_filtered_cp = figure_filtered.copy()

for i in range(height):
  for j in range(width):
    if figure_filtered[i,j]>20:
      figure_filtered_cp[i,j]=255


cv2_imshow(figure_filtered_cp)

# Décima primeira modificação efetuada na terceira imagem
# Eleventh modification made to the third image

# Mesmos passos da décima primeira modificação realizada na primeira imagem
# Same steps as the eleventh modification performed on the first image.

height = figure_filtered.shape[0]

width = figure_filtered.shape[1]

figure_filtered_cp = figure_filtered.copy()

for i in range(height):
  for j in range(width):
    if figure_filtered[i,j]>100:
      figure_filtered_cp[i,j]=255

dim = 5

c=1/9

mask = np.ones((dim,dim))*c

figure_filtered_cp = cv2.filter2D(figure_filtered_cp, -1, mask)

cv2_imshow(figure_filtered_cp)

# Décima segunda modificação efetuada na imagem
# Twelfth modification made to the image

# Mesmos passos da décima segunda modificação realizada na segunda imagem
# Same steps as the twelfth modification performed on the second image

height = figure_filtered.shape[0]
width = figure_filtered.shape[1]

figure_filtered_cp = figure_filtered.copy()

for i in range(height):
  for j in range(width):
    if figure_filtered[i,j]>20:
      figure_filtered_cp[i,j]=255

dim = 5

c=1/9

mask = np.ones((dim,dim))*c

figure_filtered_cp = cv2.filter2D(figure_filtered_cp, -1, mask)

cv2_imshow(figure_filtered_cp)